name: END TO END TEST CASES FOR ECommerce-QA-Automation

on:
  push:
    branches:
      - main # Added specific branches for push trigger
      - develop
  pull_request: # Added pull_request for more comprehensive testing
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - 'chrome'
          - 'firefox'
          - 'edge'
      runType:
        description: 'Select Runtype'
        required: true
        default: 'local'
        type: string # Corrected type from inputbox to string
      headless:
        description: 'Run tests in headless mode?'
        required: true
        default: 'true'
        type: boolean

jobs:
  Run-Selenium-Tests:
    runs-on: ubuntu-latest # CORRECTED: Changed buntu-latest to ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Debugging Steps Added ---
    - name: Debug - List Repository Contents
      run: |
        echo "Current working directory after cd: $(pwd)"
        echo "Listing contents of repository root:"
        ls -la

    # --- End Debugging Steps ---

    - name: Set up Test Environment (Java/Maven)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Selenium Tests
      run: |
        echo "Current working directory after cd: $(pwd)"
        echo "Executing Maven command:"
        
        mvn clean test -Dbrowser=${{ github.event.inputs.browser }} \
                       -Dheadless=${{ github.event.inputs.headless }} \
                       -DrunType=${{ github.event.inputs.runType }}
        
        echo "Maven command finished. Checking exit code..."
        # GitHub Actions automatically fails a step if the command exits with a non-zero code.
        # This echo just confirms execution reached this point.

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4 # Use the latest version of upload-artifact
      if: always() # Always upload the report, even if tests failed
      with:
        name: allure-report-${{ github.sha }} # Unique name for the artifact (e.g., allure-report-abcdef123)
        path: ECommerce-QA-Automation/target/allure-report # Path to your generated report directory
        # retention-days: 5 # Optional: How long to keep the artifact (default is 90 days for GitHub Free)

    # Optional: If you also want to see the Raw Allure Results (XML/JSON files)
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-${{ github.sha }}
        path: ECommerce-QA-Automation/target/allure-results
        # retention-days: 5

