name: END TO END TEST CASES FOR ECommerce-QA-Automation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser'
        required: true
        default: 'chrome'
        type: choice
        options: ['chrome', 'firefox', 'edge']
      runType:
        description: 'Select Runtype'
        required: true
        default: 'local'
        type: string
      headless:
        description: 'Run tests in headless mode?'
        required: false
        default: 'true'
        type: boolean

jobs:
  Run-Selenium-Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java & Maven
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Install Allure CLI
      run: |
        npm install -g allure-commandline --save-dev

    - name: Run Selenium Tests
      run: |
        echo "Running tests with browser=${{ github.event.inputs.browser }}, headless=${{ github.event.inputs.headless }}, runType=${{ github.event.inputs.runType }}"
        mvn clean test -Dbrowser=${{ github.event.inputs.browser }} \
                       -Dheadless=${{ github.event.inputs.headless }} \
                       -DrunType=${{ github.event.inputs.runType }}

    - name: Generate Allure Report
      run: |
        allure generate target/allure-results --clean -o target/allure-report

    - name: Upload Allure HTML Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-${{ github.sha }}
        path: target/allure-report
        if-no-files-found: error
